package com.demo.app.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import org.springframework.data.annotation.Id;

@DynamoDBTable(tableName = "customers")
public class CustomerEntity {

    @DynamoDBHashKey(attributeName = "customer_id")
    @DynamoDBAutoGeneratedKey
    private String customerId;

    @DynamoDBAttribute(attributeName = "email_address")
    private String emailAddress;

    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    public String getEmailAddress() {
        return emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
}
